version: "3.9"
services:
  
  service:
    build: Catalog.API/.
    container_name: service
    
  nginx:
    depends_on:
      - service
    build: nginx-proxy/.
    container_name: catalognginx
    ports:
      - "80:80"
      - "443:443"