version: "3.9"
services:
  
  frontend:
    build: Catalog.KO/. 
    container_name: frontend
    networks:
      - catalog-network
    
  service:
    build: Catalog.API/.
    networks:
      - catalog-network
    container_name: service
    
  nginx:
    depends_on:
      - service
      - frontend
    build: nginx-proxy/.
    container_name: catalognginx
    hostname: bookcatalog
    networks:
      - catalog-network
    ports:
      - "80:80"


networks:
  catalog-network:
    driver: bridge