version: "3.9"
services:
  
  # frontend:
  #   build: Catalog.KO/. 
  #   container_name: frontend
    
  service:
    build: Catalog.API/.
    container_name: service
    
  nginx:
    depends_on:
      - service
      # - frontend
    build: nginx-proxy/.
    container_name: catalognginx
    ports:
      - "80:80"
      - "443:443"