--Server=tcp:netietsmeer.database.windows.net,1433;Initial Catalog=netietsmeer-books;Persist Security Info=False;User ID=netietsmeer-admin;Password=@zur3Adm!#2018^;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
--CREATE TABLE Book
--(
--	BookID INT NOT NULL,
--	BookName NVARCHAR(1000) NOT NULL
--)
--delete from book
-- CREATE TABLE Book
-- (gi
--     ReadStatus NVARCHAR(255) NULL,
--     ReadRemark NVARCHAR(255) NULL,
--     Title NVARCHAR(1000) NULL,
--     Author NVARCHAR(1000) NULL,
--     Identifier NVARCHAR(1000) NULL,
--     [Language] NVARCHAR(255) NULL,
--     Category NVARCHAR(255) NULL,
--     [Subject] NVARCHAR(MAX) NULL,
    -- [Description] NVARCHAR(MAX) NULL,
--    [Folder] NVARCHAR(1000) NULL,
--    [FileName] NVARCHAR(1000) NULL
--)

-- select * from book
--insert into book values (1, 'Test boek')



--=CONCATENATE("'";A7;"','";B7;"','";C7;"','";D7;"','";E7;"','";F7;"','";G7;"','";H7;"','";I7;"','";J7;"','";K7;"'")

--INSERT INTO Book VALUES('Gelezen','','Wat als?: Serieuze wetenschappelijke antwoorden op absurde hypothetische vragen','Randall Munroe','9789000340408','nl','Roman/Leesboek','Wat als?: Serieuze wetenschappelijke antwoorden op absurde hypothetische vragen','','/','Randall_Munroe-Wat_als.epub')
begin transaction

INSERT INTO Book VALUES('Gelezen','','Wat als?: Serieuze wetenschappelijke antwoorden op absurde hypothetische vragen','Randall Munroe','9789000340408','nl','Roman/Leesboek','Wat als?: Serieuze wetenschappelijke antwoorden op absurde hypothetische vragen','','/','Randall_Munroe-Wat_als.epub')
INSERT INTO Book VALUES('','','Een onzichtbare','Ljunghill','3fbadcc745c246c6bf628f09b8a7cbc1','nl','Roman/Leesboek','','','/Ellyschoice boeken/201608','Een onzichtbare_Gertjan _9789024558087.epub')
INSERT INTO Book VALUES('','','Het familieportret','Jenna Blum','9789460231513','nl','Roman/Leesboek','','','/Ellyschoice boeken/201608','Het familieportret_Gertjan _9789460231513.epub')
INSERT INTO Book VALUES('','','Honolulu King','Anne-Gine Goemans','3cf8163b30f543639391db0fa7b4df30','nl','Roman/Leesboek','','','/Ellyschoice boeken/201608','Honolulu King_Gertjan _9789026331602.epub')
INSERT INTO Book VALUES('Gelezen','','Hou je adem in','Holly Seddon','9789026332401','nl','Roman/Leesboek','Roman','','/Ellyschoice boeken/201608','Hou je adem in_Gertjan _9789026332401.epub')
INSERT INTO Book VALUES('','','Ik zag een man','Owen Sheers','028172e012894320b660f40388601b27','nl','Roman/Leesboek','','','/Ellyschoice boeken/201608','Ik zag een man_Gertjan _9789026329593.epub')
INSERT INTO Book VALUES('','','In de wildernis','Amy Belding Brown','urn:uuid:c1d92c75745b4e30b443346aab5d1003','nl','Roman/Leesboek','','','/Ellyschoice boeken/201608','In de wildernis_Gertjan _9789044348774.epub')
INSERT INTO Book VALUES('','','Je leeft maar 1 keer','Fausto Brizzi','9789024570744','nl','Roman/Leesboek','','','/Ellyschoice boeken/201608','Je leeft maar 1 keer_Gertjan _9789024570744.epub')
INSERT INTO Book VALUES('','','Nachtfilm','Marisha Pessl','9789041420084','nl','Roman/Leesboek','Thriller','','/Ellyschoice boeken/201608','Nachtfilm_Gertjan _9789041420084.epub')
INSERT INTO Book VALUES('','','Ritueel','Isa Maron','9789044348163','nl','Roman/Leesboek','','','/Ellyschoice boeken/201608','Ritueel_Gertjan _9789044348163.epub')
INSERT INTO Book VALUES('?','','Tot waar we kijken kunnen','Inge van der Krabben','9789026331428','nl','Roman/Leesboek','Roman','','/Ellyschoice boeken/201608','Tot waar we kijken kunnen_Gertjan _9789026331428.epub')
INSERT INTO Book VALUES('Gelezen','','Alles houdt op te bestaan','Elizabeth Brundage','urn:uuid:c55b2cbd96c946da917e76a5374c2fba','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','Alles houdt op te bestaan_Gertjan _9789048830114.epub')
INSERT INTO Book VALUES('','','Alsof het voorbij is','Julian Barnes','9789045020198','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','Alsof het voorbij is_Gertjan _9789045020198.epub')
INSERT INTO Book VALUES('','','De woede van Abraham','Braam, Conny','9789045702438','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','De woede van Abraham_Gertjan _9789045702438.epub')
INSERT INTO Book VALUES('','','Judas','Astrid Holleeder','9789048825035','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','Judas_Gertjan _9789048825035.epub')
INSERT INTO Book VALUES('Gelezen','','Later als ik dood ben','Ilse Ruijters','urn:uuid:754dbe6ad901452abcbc759bb2a114ed','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','Later als ik dood ben_Gertjan _9789044348149.epub')
INSERT INTO Book VALUES('','','Memento','Emelie Schepp','urn:uuid:3285E396D9A44C5C8D2D02E94CEE7A70','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','Memento_Gertjan _9789026136443.epub')
INSERT INTO Book VALUES('','','Over het water','Hans Maarten van den Brink','9789045703381','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','Over het water_Gertjan _9789045703381.epub')
INSERT INTO Book VALUES('','','Tulpenliefde','Femke Roobol','9789026332951','nl','Roman/Leesboek','Historische Roman','','/Ellyschoice boeken/201701','Tulpenliefde_Gertjan _9789026332951.epub')
INSERT INTO Book VALUES('','','VRIJ MAN','Nelleke Noordervliet','urn:uuid:A5AFA9620BB84819AACFA901238DE449','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','Vrij man_Gertjan _9789045705514.epub')
INSERT INTO Book VALUES('','','We moeten het even over Kevin hebben','Shriver','bdc44bc8ebf34b6a806cf8e48b15b91d','nl','Roman/Leesboek','','','/Ellyschoice boeken/201701','We moeten het even over Kevin hebben_Gertjan _9789025439958.epub')
INSERT INTO Book VALUES('Gelezen','','De huurmoeder','Tania Heimans','urn:uuid:c6d18abd602e41ae9b4314aa8443a857','nl','Roman/Leesboek','','','/Ellyschoice boeken/201702','De huurmoeder.epub')
INSERT INTO Book VALUES('','','Enkeltje Ierland','Charlotte de Monchy','urn:uuid:fc86c03a0156baab900b110525cef882','nl','Roman/Leesboek','','','/Ellyschoice boeken/201702','Enkeltje Ierland.epub')
INSERT INTO Book VALUES('','','Geboren verliezers','Elvin Post','urn:uuid:56d0a5ac6c60413aba9f212492537bfc','nl','Roman/Leesboek','','','/Ellyschoice boeken/201702','Geboren verliezers.epub')
INSERT INTO Book VALUES('','','Magycker 1 - De Klauw','Adrian Stone','urn:uuid:58c60f50f7ea47cdb25b3f2334caa64e','nl','Roman/Leesboek','','De Klauw is deel 1 van Adrian Stone’s nieuwe fantasy-reeks Magycker. Stone is bekend van de Duivel-trilogie en het Rune-tweeluik. Al eeuwenlang hebben de Magyckers van het eiland Aimerey een monopolie op magie in de wereld. Wie goed betaalt kan bijna elke spreuk kopen die hij wil. Maar de spreuken zijn maar van tijdelijke duur, en voordat een Magycker zijn spreuk kan herhalen wordt zijn geheugen gewist. Alleen de allerrijksten kunnen dus genieten van de giften van de Magyckers. Als een delegatie uit Aimerey het dorpje van Marit en haar autistische broertje Auric aandoet, kunnen ze het daarom bijna niet geloven. De grote rotsblokken die de enige toegang tot het dorp versperren zijn weliswaar een financiële domper voor de handel, maar niemand had ooit gedacht dat het bestuur de Magyckers zou betalen om ze te laten weghalen. Als iemand vervolgens de spreuk van de Magyckers herhaalt, breekt de hel los. Vrij gebruik van een spreuk brengt het hele bestaan van Aimerey in gevaar, en dat zullen de Magyckers koste wat kost voorkomen. Maar laat nou net Auric degene zijn die de spreuk kan herhalen... Adrian Stone (1958) is de grootste Nederlandse fantasy-auteur van het moment. Magycker 1 – De Klauw is zijn zesde boek en het begin van een compleet nieuwe serie.','/Ellyschoice boeken/201702','Magycker 1 - De klauw.epub')
INSERT INTO Book VALUES('Gelezen','','Naamloos','Pepijn Lanen','urn:uuid:265306858aa04814b8cd5b93c1b483b1','nl','Roman/Leesboek','','','/Ellyschoice boeken/201702','Naamloos.epub')
INSERT INTO Book VALUES('','','Schaduwkinderen','Linda Jansma','9789461092564','nl','Roman/Leesboek','','','/Ellyschoice boeken/201702','Schaduwkinderen.epub')
INSERT INTO Book VALUES('','','Verzwegen','René Appel','9789026333736','nl','Roman/Leesboek','Literaire Thriller','','/Ellyschoice boeken/201702','Verzwegen.epub')
INSERT INTO Book VALUES('','','Zijspoor','Josha Zwaan','9789025905101','nl','Roman/Leesboek','','','/Ellyschoice boeken/201702','Zijspoor.epub')
INSERT INTO Book VALUES('Gelezen','','Blind date','Marelle Boersma','9789461092472','nl','Roman/Leesboek','','','/Ellyschoice boeken/201703','Blind date.epub')
INSERT INTO Book VALUES('?','Niet zeker, lijkt dat ik deze gelezen heb, zij zakt door het ijs?','De consequenties','Niña Weijers','urn:uuid:2F65074F4C174E03ADAA4F9BC8F83268','nl','Roman/Leesboek','','','/Ellyschoice boeken/201703','De consequenties.epub')
INSERT INTO Book VALUES('Gelezen','','De greppel','Herman Koch','9789026332302','nl','Roman/Leesboek','Roman','','/Ellyschoice boeken/201703','De greppel.epub')
INSERT INTO Book VALUES('Gelezen','','DIJK','H.M. van den Brink','urn:uuid:C47C7CD5B13C4D1F87646FCC122A9D43','nl','Roman/Leesboek','','','/Ellyschoice boeken/201703','Dijk.epub')
INSERT INTO Book VALUES('','','Eindspel','Isa Maron','9789044348590','nl','Roman/Leesboek','','','/Ellyschoice boeken/201703','Eindspel.epub')
INSERT INTO Book VALUES('Gelezen','','Gestrand met een miljonair','Jessica Clare','urn:uuid:347201ab2d90970613e2981d4ec8d579','nl','Roman/Leesboek','','','/Ellyschoice boeken/201703','Gestrand met een miljonair.epub')
INSERT INTO Book VALUES('','','Het Amazoneverbond','Ad van de Lisdonk','9789461090928','nl','Roman/Leesboek','','','/Ellyschoice boeken/201703','Het Amazoneverbond.epub')
INSERT INTO Book VALUES('','','Iets ouds en iets blauws','Katie Fforde','urn:uuid:96DD807E968443F7BB872F257ADAFA21','nl','Roman/Leesboek','','','/Ellyschoice boeken/201703','Iets ouds en iets blauws.epub')
INSERT INTO Book VALUES('','','De dood van Murat Idrissi','Tommy Wieringa','9789048836864','nl','Roman/Leesboek','','','/Ellyschoice boeken/201705','De dood van Murat Idrissi.epub')
INSERT INTO Book VALUES('Gelezen','','Domina','L.S. Hilton','urn:uuid:65ece6f9cc7647caa5505bb6baa71c15','nl','Roman/Leesboek','','','/Ellyschoice boeken/201705','Domina.epub')
INSERT INTO Book VALUES('','','Een meisje loos','Ton van der Lee','9789026335631','nl','Roman/Leesboek','Roman','','/Ellyschoice boeken/201705','Een meisje loos.epub')
INSERT INTO Book VALUES('','','Offer voor een verloren zaak','Hugo Luijten','urn:uuid:0c437071ef074dc3b62cebbbba8b97ea','nl','Roman/Leesboek','','','/Ellyschoice boeken/201705','Offer voor een verloren zaak.epub')
INSERT INTO Book VALUES('','','PAN','Maes','urn:uuid:2929C561096A4CBE8A5BD79729F2EA79','nl','Roman/Leesboek','Misdaadroman','Misdaadroman','/Ellyschoice boeken/201705','Pan.epub')
INSERT INTO Book VALUES('','','Pogingen iets van het leven te maken','Hendrik Groen','Groen_PogingenIetsVanHetLevenTeMaken_9789402301663','nl','Roman/Leesboek','','','/Ellyschoice boeken/201705','Pogingen iets van het leven te maken.epub')
INSERT INTO Book VALUES('','','Stil in de stad','Milou van der Will','urn:uuid:1b900e2d20764edfad8acb7d082ae402','nl','Roman/Leesboek','','','/Ellyschoice boeken/201705','Stil in de stad.epub')
INSERT INTO Book VALUES('','','Zie_mij','','urn:uuid:29d919dd24f54384be78b447c9dc299b','nl','Roman/Leesboek','','','/Ellyschoice boeken/201705','Zie mij.epub')
INSERT INTO Book VALUES('','','Als de rododendron bloeit','Santa Montefiore','9789402305920','nl','Roman/Leesboek','Thriller','','/Ellyschoice boeken/201706','Als de rododendron bloeit.epub')
INSERT INTO Book VALUES('Gelezen','','Bloedlink','Marianne en Theo Hoogstraaten','9789461091956','nl','Roman/Leesboek','','','/Ellyschoice boeken/201706','Bloedlink.epub')
INSERT INTO Book VALUES('','','De juiste man','Max van Olden','9789026335884','nl','Roman/Leesboek','Literaire thriller','','/Ellyschoice boeken/201706','De juiste man.epub')
INSERT INTO Book VALUES('Gelezen','','De voyeur','Aloka Liefrink','urn:uuid:20D537B4B3AD46698983BED49016A477','nl','Roman/Leesboek','Psychologische thriller','Als de 27-jarige Lisa, succesvol debuterend auteur, ontdekt dat haar vriend Sander haar bedriegt met Miro, een prostituee uit het voormalige Oostblok, komt haar hele leven op de helling te staan. Tijdens een signeersessie loopt ze de knappe, mysterieuze Richard, met wie ze ooit een korte romance had, opnieuw tegen het lijf. Hij is flamboyant, werkt als gesprekstherapeut en biedt haar een luxueuze flat aan tegen een vriendenprijs. Lisa tuimelt halsoverkop in een nieuw leven maar dan komt ze er langzaamaan achter dat Richard een erg gewelddadig kantje heeft. Met welke motieven is Richard opnieuw binnengedrongen in het bestaan van Lisa? En hoe is hij gelinkt aan Miro? De voyeur is een onthutsende en ijzingwekkende psychologische thriller met een vleugje erotiek. Aloka Liefrink (1979), geboren in Kerala te India en geadopteerd door een Nederlands-Vlaams echtpaar, debuteerde succesvol in 2010 met haar sterk autobiografische roman Verweesd. Haar thrillers worden door de pers en haar schare aan fans omschreven als beklijvende pageturners. Aloka schreef in 2014 een bestseller in co-auteurschap.','/Ellyschoice boeken/201706','De voyeur.epub')
INSERT INTO Book VALUES('','','Doodverklaard','Lisa Gardner','9789044337051','nl','Roman/Leesboek','','','/Ellyschoice boeken/201706','Doodverklaard.epub')
INSERT INTO Book VALUES('','','Het dameskoor van Chilbury','Jennifer Ryan','urn:uuid:4849bff5a7ef43a1925df49e4f241495','nl','Roman/Leesboek','','','/Ellyschoice boeken/201706','Het dameskoor van Chilbury.epub')
INSERT INTO Book VALUES('Gelezen','','Naar huis','Harlan Coben','9789402307610','nl','Roman/Leesboek','Thriller','','/Ellyschoice boeken/201706','Naar huis.epub')
INSERT INTO Book VALUES('?','','Tegen beter weten in','Jane Fallon','776e5e5630f332c7b4f575707a80a0f4','nl','Roman/Leesboek','','','/Ellyschoice boeken/201706','Tegen beter weten in.epub')
INSERT INTO Book VALUES('','','De laatste roos van de zomer','Santa Montefiore','9789402308365','nl','Roman/Leesboek','Roman','','/Ellyschoice boeken/201708','De laatste roos van de zomer.epub')
INSERT INTO Book VALUES('Gelezen','','De verbeelding','Harlan Coben','9789402303452','nl','Roman/Leesboek','Thriller','','/Ellyschoice boeken/201708','De verbeelding.epub')
INSERT INTO Book VALUES('Gelezen','','Fatale vriendschap','Paul De Bruyn','urn:uuid:A3A2AFD3C8054021B671500DC9914CBA','nl','Roman/Leesboek','thriller','thriller','/Ellyschoice boeken/201708','Fatale vriendschap.epub')
INSERT INTO Book VALUES('','','Gebroken','BA Paris','9789402752762','nl','Roman/Leesboek','Thriller','','/Ellyschoice boeken/201708','Gebroken.epub')
INSERT INTO Book VALUES('','','Het verraad van Julia','Brenda Meuleman','9789026334108','nl','Roman/Leesboek','Historische Roman','','/Ellyschoice boeken/201708','Het verraad van Julia.epub')
INSERT INTO Book VALUES('Gelezen','','Hoofdzaak','Mariska Overman','9789461092656','nl','Roman/Leesboek','','','/Ellyschoice boeken/201708','Hoofdzaak.epub')
INSERT INTO Book VALUES('','','Iene miene mutte','M.J. Arlidge','9789402302301','nl','Roman/Leesboek','Thriller','','/Ellyschoice boeken/201708','Iene miene mutte.epub')
INSERT INTO Book VALUES('','','Ik zal verborgen zijn','Eline Rosenhart','9789029721073','nl','Roman/Leesboek','','','/Ellyschoice boeken/201708','Ik zal verborgen zijn.epub')
INSERT INTO Book VALUES('','','Overzee','Marlies Brenters','41cd79b0c8214929a605cc9ada6f4e03','nl','Roman/Leesboek','','','/Ellyschoice boeken/201708','Overzee.epub')
INSERT INTO Book VALUES('','','Als we elkaar terugzien','Kristin Harmel','harmel_alsweelkaarterugzien_9789402307771','nl','Roman/Leesboek','','Columniste Emily denkt dat ze alles kwijt is: haar baan, haar familie en haar grote jeugdliefde. Dan ontvangt ze van een geheime afzender een prachtig, mysterieus schilderij: een portret van een vrouw, die ze direct herkent als een jonge versie van haar onlangs overleden grootmoeder. Er staat geen afzender bij, alleen een handgeschreven briefje met de boodschap: Hij is altijd van haar blijven houden. Emily besluit op onderzoek uit te gaan. Wie heeft haar het schilderij gestuurd? Wie heeft het gemaakt? En kende de schilder haar oma? Ze komt op het spoor van dramatische gebeurtenissen in oorlogskampen waar Duitse krijgsgevan-genen werkten voor Amerikaanse boeren, en soms verliefd werden op Amerikaanse vrouwen. Door wat ze ontdekt komen ook Emily’s eigen levensverhaal, de relatie met haar vader en hun pijnlijke geschiedenis in een ander licht te staan. Zal ze eindelijk de kracht vinden om de confrontatie met het verleden aan te gaan?','/Ellyschoice boeken/201711','Als we elkaar terugzien.epub')
INSERT INTO Book VALUES('','','De zwarte brug','Erik Vlaminck','9789460013638','nl','Roman/Leesboek','','','/Ellyschoice boeken/201711','De zwarte brug.epub')
INSERT INTO Book VALUES('','','Dood spel','Harlan Coben','9789460233937','nl','Roman/Leesboek','Thriller','','/Ellyschoice boeken/201711','Dood spel.epub')
INSERT INTO Book VALUES('','','Grijs gebied','Marion Pauw','9789059652927','nl','Roman/Leesboek','Literaire Thriller','','/Ellyschoice boeken/201711','Grijs gebied.epub')
INSERT INTO Book VALUES('','','Helemaal_het_einde','','urn:uuid:29d919dd24f54384be78b447c9dc299b','nl','Roman/Leesboek','','','/Ellyschoice boeken/201711','Helemaal het einde.epub')
INSERT INTO Book VALUES('Gelezen','','Niks','Koen Gubbels','9789026335426','nl','Roman/Leesboek','Literaire Thriller','','/Ellyschoice boeken/201711','Niks.epub')
INSERT INTO Book VALUES('','','Ragdoll','','urn:uuid:29d919dd24f54384be78b447c9dc299b','nl','Roman/Leesboek','','','/Ellyschoice boeken/201711','Ragdoll.epub')
INSERT INTO Book VALUES('','','Uit liefde, meneer Tuschinski','Tanya Commandeur','9789026339646','nl','Roman/Leesboek','Historische Roman','','/Ellyschoice boeken/201711','Uit liefde, meneer Tuschinski.epub')
INSERT INTO Book VALUES('','','Slender Man','Guido Eekhaut','9789460015724','nl','Roman/Leesboek','','','/Ellyschoice boeken/201711-Free book','Slender Man.epub')
INSERT INTO Book VALUES('','','De Poppendokter','Diane Broeckhoven','9789460012815','nl','Roman/Leesboek','','','/Ellyschoice boeken/201712','De Poppendokter.epub')
INSERT INTO Book VALUES('','','Een leven na jou','Jojo Moyes','9789026139567','nl','Roman/Leesboek','','','/Ellyschoice boeken/201712','Een leven na jou.epub')
INSERT INTO Book VALUES('','','Een nieuw begin','Angelique Haak','9789461092885','nl','Roman/Leesboek','','','/Ellyschoice boeken/201712','Een nieuw begin.epub')
INSERT INTO Book VALUES('','','Een tragedie in New York','Maurice Seleky','9789026340598','nl','Roman/Leesboek','Roman','','/Ellyschoice boeken/201712','Een tragedie in New York.epub')
INSERT INTO Book VALUES('','','Heelmeester','','urn:uuid:29d919dd24f54384be78b447c9dc299b','nl','Roman/Leesboek','','','/Ellyschoice boeken/201712','Heelmeester.epub')
INSERT INTO Book VALUES('Gelezen','','Lieve Amy','Helen Callaghan','9789026334214','nl','Roman/Leesboek','Literaire Thriller','','/Ellyschoice boeken/201712','Lieve Amy.epub')
INSERT INTO Book VALUES('','','Ten oosten van de afgrond','Thomas Engström','9789026333071','nl','Roman/Leesboek','Literaire Thriller','','/Ellyschoice boeken/201712','Ludwig Licht-kwartet 4 - Ten oosten van de afgrond.epub')
INSERT INTO Book VALUES('','','Vijf spannende verhalen','Nicci French','9789026342868','nl','Roman/Leesboek','Roman','','/Ellyschoice boeken/201712','Vijf spannende verhalen.epub')
INSERT INTO Book VALUES('','','Dagboek van een getuige','Astrid Holleeder','9789048843527','nl','Roman/Leesboek','','','/Ellyschoice boeken/201801','Dagboek van een getuige.epub')
INSERT INTO Book VALUES('','','De duiventunnel. Verhalen uit mijn leven','John le Carré','carré_duiventunnel_9789024571661','nl','Roman/Leesboek','','Van zijn jaren in dienst van de Britse inlichtingendienst tijdens de Koude Oorlog, tot een carrière als schrijver, die hem van het door oorlog verscheurde Cambodja naar Beiroet bracht, op het heftigste moment van de Israëlische invasie in 1982, tot Rusland voor én na het neerhalen van de Berlijnse Muur, heeft John le Carré altijd geschreven vanuit het hart van de moderne tijd. In De duiventunnel, zijn eerste verzameling memoires, is John le Carré even geestig als scherpzinnig – en hij bespeurt in de gebeurtenissen waarvan hij getuige is dezelfde morele ambiguïteit waarmee hij ook zijn romans doordrenkt. Of hij nu schrijft over de papegaai in een hotel in Beiroet die het geluid van een machinegeweer perfect kon nadoen, of over een bezoek aan musea met nog niet begraven doden in Rwanda na de genocide, of dat hij de jaarwisseling viert met Yasser Arafat, of een Duitse terroriste interviewt in haar gevangenis in de Negev-woestijn, John le Carré beschrijft elke gebeurtenis met overgave en humor. Nu eens laat hij ons schateren, dan weer nodigt hij ons uit om nog eens goed na te denken over de gebeurtenissen en de mensen die wij meenden te begrijpen. Bovenal schetst John le Carré ons een beeld van de omzwervingen van een schrijver over een periode van meer dan zestig jaar, en van zijn eigen speurtocht naar de menselijke vonk die de personages in zijn romans zoveel overtuiging en bezieling heeft gegeven.','/Ellyschoice boeken/201801','De Duiventunnel.epub')
INSERT INTO Book VALUES('','','Jij, ik en de zee','Sandy Taylor','9789043528733','nl','Roman/Leesboek','','','/Ellyschoice boeken/201801','Jij, ik en de zee.epub')
INSERT INTO Book VALUES('Lezen','','Mijn beeld van jou','Susan van Eyck','urn:uuid:f356c48cc7b9465a8754b4a350015353','nl','Roman/Leesboek','','','/Ellyschoice boeken/201801','Mijn beeld van jou.epub')
INSERT INTO Book VALUES('','','Johan Cruijff - Mijn verhaal. De autobiografie','Johan Cruijff','ISBNebook:9789046821565','nl','Roman/Leesboek','Sportbiografie - autobiografie','"Voetbalkunstenaar Johan Cruijff is een icoon. Hij was misschien wel de beste speler aller tijden. De invloed van zijn speelstijl en voetbalfilosofie was en is groot. Hij is een held, een voorbeeld, een leermeester. Zowel voor- als tegenstanders luisterden geboeid als hij het woord nam, op zijn onnavolgbare wijze. Johan Cruijff is van ons allemaal en daardoor heeft iedereen zijn ‘eigen’ Johan: een mengeling van feit en fictie. Nu is dan het woord aan hemzelf, in deze meeslpende autobiografie. Hierin geeft hij zíjn visie op alles wat hem bezighield, op het voetbal en op het leven. Johan Cruijff – Mijn verhaal is een heel persoonlijk boek, het enige met zijn éígen verhaal. Als je het leest, is het alsof hij zelf tegen je praat. Eindelijk leren wij de echte Johan kennen.','/Ellyschoice boeken/201801','Mijn verhaal.epub')
INSERT INTO Book VALUES('','','Nog één keer feest','Liane Moriarty','urn:uuid:378D2CB0C3E34599A5715DFEC97B9688','nl','Roman/Leesboek','','','/Ellyschoice boeken/201801','Nog één keer feest.epub')
INSERT INTO Book VALUES('','','Portret van een man','Jens Christian Grøndahl','urn:uuid:FA06251D3A4D49B0AE3A0648C9463158','nl','Roman/Leesboek','','','/Ellyschoice boeken/201801','Portret van een man.epub')
INSERT INTO Book VALUES('Gelezen','','Weg van jou','N.I. Monteny','1466919549ec4c0ca9322418a37756eb','nl','Roman/Leesboek','','‘Basorexie.’ ‘Wat?’ ‘Ken je dat woord, Helena?’ Hij zegt haar naam heel nadrukkelijk. Ze schudt van nee. ‘Het is een lelijk woord voor een geweldig gevoel. De plotse aandrang om iemand te kussen.’ Ze slikt. Ze herkent het gevoel. Heel even zitten ze stil, alsof iemand ergens op een pauzeknop geduwd heeft, hun gezicht op amper een paar centimeter van elkaar. Helena glimlacht, ze weet wat er nu komt. Net als Klaus zich vooroverbuigt, gaat de deur van de gang open. ‘Hola!’ Helenas nichtje kijkt verbaasd. ‘Jullie zitten gewoon wat te kussen. Jezus, op jullie leeftijd.’ Met haar neus in de lucht loopt de tiener de keuken in. Terwijl alleenstaande moeder én eeuwige vrijgezel Helena op haar nichtjes past en een acute aanval van basorexie probeert te bedwingen, kust haar schoonzus Anouk op een bruiloft een man die niet de hare is. In een garderobekast. Patriarch en weduwnaar Bob rijgt ondertussen de internetdates aan elkaar en Helena’s zoon vraagt zich af of samenwonen met zijn vriendin wel zo’n goed idee was. Er raast een storm door de familie Van Antwerpen die de relatiekaarten stevig door elkaar schudt. En dan is er nog dat telefoontje van een televisiezender.','/Ellyschoice boeken/201801','Weg van jou.epub')
INSERT INTO Book VALUES('Gelezen','','Zondeval','Marianne en Theo Hoogstraaten','9789461092724','nl','Roman/Leesboek','','','/Ellyschoice boeken/201801','Zondeval.epub')
INSERT INTO Book VALUES('','','Voor uw liefde','Mario Vargas Llosa','urn:uuid:97F8383E98EC4AF2B65C5B169A71F334','nl-NL','','','','/Ellyschoice boeken/201802','Voor uw liefde.epub')
INSERT INTO Book VALUES('Lezen','','Oker','Ellen Verstrepen','urn:uuid:DE14A1E6EDC7432C9B3EA6DD523499DB','nl-NL','','roman','','/Ellyschoice boeken/201802','Oker.epub')
INSERT INTO Book VALUES('','','Vrouwen die vreemdgaan','','urn:uuid:29d919dd24f54384be78b447c9dc299b','nl-NL','','','','/Ellyschoice boeken/201802','Vrouwen die vreemdgaan.epub')
INSERT INTO Book VALUES('','','Schipper en Zn.','Cobi van Baars','urn:uuid:DBA82223E54740A69EFE5AB807212373','nl-NL','','','','/Ellyschoice boeken/201802','Schipper & zn..epub')
INSERT INTO Book VALUES('Lezen','','Carve the Mark','Veronica Roth','9789000352234','nl','Young Adult','','','/Ellyschoice boeken/201802','Carve the Mark.epub')
INSERT INTO Book VALUES('','','Onder de radar','Lee Child','9789024573172','nl','','','Hamburg, 1996. Jack Reacher is naar Duitsland vertrokken voor een zeer geheime missie. Een jihadistische cel heeft daar een boodschap gekregen: de Amerikaan wil honderd miljoen dollar. Wat is er gaande? Jack Reacher begeeft zich op verraderlijk terrein. Hij krijgt te maken met nieuwe, geduchte tegenstanders, dubbele agenda’s en keiharde actie. Als Reacher het spel mee wil spelen, is alles geoorloofd – zolang hij onder de radar blijft. Lee Child is winnaar van de prestigieuze Diamond Dagger Award 2013. De nieuwste Jack Reacher-film Never Go Back (met Tom Cruise in de hoofdrol) is een groot succes in Nederland en Vlaanderen.','/Ellyschoice boeken/201802','Onder de radar.epub')
INSERT INTO Book VALUES('','','De brekerjongens','Ellen Marie Wiseman','urn:uuid:2C73A5A5D5FB4BFF8166B4B89EC31D1A','nl-NL','','','','/Ellyschoice boeken/201802','De brekerjongens.epub')
INSERT INTO Book VALUES('','','De-wilden1','','urn:uuid:29d919dd24f54384be78b447c9dc299b','nl-NL','','','','/Ellyschoice boeken/201802','De Franse Bruiloft #1 - De wilden.epub')
INSERT INTO Book VALUES('','','Vergeten reus','Kazuo Ishiguro','urn:uuid:349ff1dc61414d3387e8a54975547f06','nl-NL','','','','/Ellyschoice boeken/201803','Vergeten reus.epub')
INSERT INTO Book VALUES('Gelezen','','Onderuitgehaald','Loes den Hollander','9789461092915','nl-NL','','','','/Ellyschoice boeken/201803','Onderuitgehaald.epub')
INSERT INTO Book VALUES('','','Hoe alles moest beginnen','Thomas Verbogt','ISBNebook:9789046822913','nl','','Roman','Twee kinderen, Thomas en Licia, gaan met elkaar het verzonnen leven aan, want het echte leven vertrouwen ze niet. Aan hun tijd samen komt abrupt een einde. Ze moeten elkaar loslaten, maar kunnen dat niet. In Hoe alles moest beginnen volgen we Thomas en Licia als kinderen, twintigers, veertigers en zestigers. Hoe gaat de tijd met hen om? Hoe behouden zij hun verzonnen leven? Hoe blijven hun levens verweven en welke betekenis hebben zij voor elkaar? Hoe alles moest beginnen is een stilistische parel, een roman over de liefde, de tijd, en de kracht van het verzinnen.','/Ellyschoice boeken/201803','Hoe alles moest beginnen.epub')
INSERT INTO Book VALUES('','','De samaritaan','Mason Cross','3c522392bac9439299460be31951999e','nl','','','Wanneer het lichaam van een jonge vrouw wordt gevonden, herkent detective Jessica Allen de modus operandi van de moordenaar. Een sadistische moordenaar aast op vrouwen met autopech. De pers heeft hem ‘de samaritaan’ genoemd, maar zonder aanwijzingen en sporen loopt het politieonderzoek al snel vast. Dan komt manhunter Carter Blake in beeld, met de opvallende gave om de volgende stappen van de samaritaan te kunnen voorspellen. Jessica Allen en haar collega’s zijn echter achterdochtig, want hun nieuwe bondgenoot lijkt verdacht veel op de man die ze zoeken… De samaritaan van Mason Cross is het tweede deel in de verslavende thrillerserie rond Carter Blake.','/Ellyschoice boeken/201803','De Samaritaan.epub')
INSERT INTO Book VALUES('','','Stadspanters','Astrid Haerens','dafddffe30934bf097b843b395f14ce6','nl','','','Stadspanters is een intens portret van mensen die worstelen met identiteit, dromen en dwaalwegen. Amar Moussaoui is overleden. Zijn plotse dood brengt zijn dochter Rim, zijn zoon Aadam en hun jeugdvriend Eloïc na jaren opnieuw samen in het appartement van het Brusselse woonblok Sans Soucis. Rim is een rijzende ster in de media. Aadam werkt als ontwikkelingssamenwerker in Kigali. Eloïc probeert als alleenstaande vader van drie kinderen vooral het hoofd boven water te houden. De drie twintigers, die samen opgroeiden in de rand van Brussel, worden geconfronteerd met de onverteerde stukken uit hun verleden en hun uiteenlopende werelden, waarin ze zich voortbewegen als panters: snel maar behoedzaam, soepel maar solitair.','/Ellyschoice boeken/201803','Stadspanters.epub')
INSERT INTO Book VALUES('','','Dodelijke_affaire','','urn:uuid:29d919dd24f54384be78b447c9dc299b','nl-NL','','','','/Ellyschoice boeken/201803','Dodelijke affaire.epub')
INSERT INTO Book VALUES('','','Niet de race maar de reis','Jolanda Linschoten','ISBN9789024566822','nl-NL','','','Hoe is het om in je eentje dwars door Engeland, Wales en Schotland te rennen? Ultraloopster Jolanda Linschooten deed het. Ze liep in zes weken een trailrun van 2000 km, in de eenzaamheid van de ruige natuur, door weer en wind. Het was heerlijk – ze voelde de snelheid in haar benen, in haar hele wezen, en ze was één met de elementen. Maar het was ook afzien door kou en intense vermoeidheid. De reis keerde haar emotioneel binnenstebuiten, maar uiteindelijk overwon ze zichzelf. Jolanda Linschooten is avonturier en fotografe. Bovendien is ze een van Nederlands sterkste ultratrail-loopsters. Ze heeft een reeks reisboeken op haar naam staan en houdt presentaties over haar tochten. In Niet de race maar de reis vertelt ze wat een extreme voetreis met haar doet.','/Ellyschoice boeken/201803','Niet de race maar de reis.epub')
INSERT INTO Book VALUES('','','De vuurtorenwachter','Camilla Läckberg','9789041418715','nl','','','','/Ellyschoice boeken/201803','Vuurtorenwachter.epub')
INSERT INTO Book VALUES('','','Victoria','','urn:uuid:29d919dd24f54384be78b447c9dc299b','nl-NL','','','','/Ellyschoice boeken/201804','Victoria.epub')
INSERT INTO Book VALUES('','','Ik zie jou','Clare Mackintosh','urn:uuid:493CA141380B4526ABA0BD8209FA9051','nl-NL','','','','/Ellyschoice boeken/201804','Ik zie jou.epub')
INSERT INTO Book VALUES('','','Chateau Provence','Marelle Boersma','9789461093202','nl-NL','','','','/Ellyschoice boeken/201804','Chateau de Provence.epub')
INSERT INTO Book VALUES('','','De Vliegende Hollander','Frank van Pamelen','9789026337451','nl','','Roman','','/Ellyschoice boeken/201804','De Vliegende Hollander.epub')
INSERT INTO Book VALUES('','','Schoonheid raast in mij tot ik sterf','Kamaledin Hazim','a19b93a00e8b4820abc488b2ff421ec7','nl','','','Hazim Kamaledin is dood. Vermoord door terroristen of omgekomen tijdens een Amerikaans bombardement. Niemand weet er het fijne van. Tijdens de dictatuur van Saddam Hoessein was Hazim de alom geprezen regisseur van het bekroonde Schoonheid raast in mij tot ik sterf. Met die film nam hij Saddam op de korrel, tot de censuur er zich mee bemoeide en er een zoetsappig promotieverhaal van maakte. Tijdens zijn leven had Hazim Kamaledin niet veel vrienden. Maar nu hij er niet meer is, valt het aantal vrienden niet meer te tellen. En net nu begint zijn familie ruzie te maken over de plek waar hij, de ketter (en links op de koop toe), begraven zou moeten worden. Schoonheid raast in mij tot ik sterf is een wonderlijke roman waarin Hazim Kamaledin – de schrijver die gezond en wel in leven is – toont hoe fictie sterker kan zijn dan de werkelijkheid. Alles in de wereld van Schoonheid raast in mij tot ik sterf wordt door de oorlog tot as herleid, behalve de herinnering aan wat ooit menselijkheid was en de humor waarmee Hazim Kamaledin het lot van zijn dode dubbelganger beschrijft.','/Ellyschoice boeken/201804','Schoonheid raast in mij tot ik sterf.epub')
INSERT INTO Book VALUES('','','Spiegel','Cara Delevingne','9789402753776','nl','','Roman','','/Ellyschoice boeken/201804','Spiegel.epub')
INSERT INTO Book VALUES('','','Herberekening','Frederik Baas','9789026340185','nl','','Thriller','','/Ellyschoice boeken/201804','Herberekening.epub')
INSERT INTO Book VALUES('','','Lek','Don Winslow','978940252694','nl','','Thriller','','/Ellyschoice boeken/201804','Lek.epub')

commit